Fix undefined `to_h` method in Termin class
Strech/termin_de pull request #10
Opened 2021-06-12 20:46 UTC by delucis

This PR fixes a bug when passing a custom command to the CLI. For example, if you wanted to automatically open a link when a termin is found:

```
$ termin_de --dry-run -c "open '%{link}'"
```

The command template is [passed the result of `termin.to_h`](https://github.com/Strech/termin_de/blob/bb0b47c05fc0dc077a263aac4b369a872e831c21/lib/termin_de/loop.rb#L59), but currently `to_h` is undefined, so the tool crashes. I see that in the past the `Termin` class used a struct which would have had `to_h` defined by default, but this is no longer the case, so I’ve added a simple implementation.

These are probably the first lines of Ruby I’ve ever written, so there a might be a nicer way of converting public class properties to a hash, but I can confirm this works :-)

2021-06-15 08:25 UTC, Strech requested changes
Hey @delucis thanks for your contribution, I have a small style suggestion and ready to ship it!

2021-06-15 08:25 UTC, Strech commented on lib/termin_de/termin.rb
> +      {:link => @link,:date => @date}
```suggestion
      {link: @link, date: @date}
```

2021-06-15 08:33 UTC, delucis commented
Changed! Thanks for the tool :-)

2021-06-16 10:17 UTC, Strech approved these changes

2021-06-16 10:17 UTC, merged

2021-06-16 10:18 UTC, Strech commented
Thanks for your contribution, I appreciate it! 🎉